name: "Build Docker Image"
run-name: "BUILD --> ${{ inputs.imageTag }} FOR ${{ inputs.GCPAccount }}"
on:
  workflow_dispatch:
    inputs:
      GCPAccount:
        type: environment
        description: "GCP account for image"
        required: true
      imageTag:
        description: "Release version"
        required: true

jobs:
  docker-build:
    environment: ${{ inputs.GCPAccount }}
    runs-on: ubuntu-latest
    env:
      WEB_BACKEND_IMAGE_URL: gcr.io/${{ inputs.GCPAccount }}/web-backend-image:${{ inputs.imageTag }}

    steps:
      - name: "Github Checkout"
        uses: actions/checkout@v3

      - name: "Authenticate with GCP"
        id: "gcloudauth"
        uses: "google-github-actions/auth@v1.1.1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Docker build
        run: |-
          docker build --no-cache -t ${{ env.WEB_BACKEND_IMAGE_URL }} .

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ inputs.GCPAccount }}
          install_components: gke-gcloud-auth-plugin

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet --account ${{ inputs.GCPAccount }}

      - name: Push Compose Build
        run: |-
          docker push ${{ env.WEB_BACKEND_IMAGE_URL }}
