name: Lint

on:
  # Trigger the workflow on a pull request
  pull_request:
    types: [synchronize, opened, edited, ready_for_review, reopened, unlocked]

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-linter:
    name: Check Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
