name: release
on:
  pull_request:
    types: [synchronize, opened, edited, ready_for_review, reopened, unlocked]
    branches: [main, development]
  push:
    branches: [main, development]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/config/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-release-label:
    needs: auto-label
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'release:true')
    outputs:
      should-run: ${{ steps.check-label.outputs.should-run }}

    steps:
      - name: Check for release label
        id: check-label
        run: echo "::set-output name=should-run::true"

  release-checks:
    needs: check-release-label
    if: needs.check-release-label.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Extract package version
        id: package-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Tag PR with Version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          gh pr edit "$PR_NUMBER" --add-label "version:$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Create Release Pull Request or release
        uses: changesets/action@v1
        id: changesets
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ github.action.label.name == 'release:true' }}
