name: Release Checks
on:
  label:
    types: [created, edited, deleted]
  pull_request:
    types: [synchronize, opened, edited, ready_for_review, reopened, unlocked]
    branches: [main, development]
  push:
    branches: [main, development]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write
  statuses: write
  actions: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'release:true')
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/config/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: contains(github.event.pull_request.labels.*.name, 'release:true')
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Extract package version
        id: package-version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Update PR title with version
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
            PACKAGE_VERSION="${{ env.PACKAGE_VERSION }}" # Make sure this is set in your env or job context
            RELEASE_PREFIX="Release "

            # Fetch the current PR title
            PR_TITLE="$(gh pr view "$PR_NUMBER" --json title -q .title)"
            echo "Current PR Title: $PR_TITLE"

            # Check if the version is already in the title
            if [[ "$PR_TITLE" != *"$RELEASE_PREFIX$PACKAGE_VERSION"* ]]; then
              # If not, append the version to the PR title
              NEW_TITLE="$RELEASE_PREFIX$PACKAGE_VERSION - $PR_TITLE"
              echo "Updating PR title to: $NEW_TITLE"
              gh pr edit "$PR_NUMBER" --title "$NEW_TITLE"
            else
              echo "Version is already present in the PR title. No update needed."
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION}}

      - name: Check for Changeset file
        id: check
        run: |
          echo "Checking for Changeset files..."
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Ref: ${{ github.head_ref }}"
          CHANGES_FOUND=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '^\.changeset/' | wc -l)
          if [ "$CHANGES_FOUND" -eq "0" ]; then
            echo "No Changeset found for PR labeled with 'release:true'."
            echo "CHANGESET_PRESENT=false" >> $GITHUB_ENV
          else
            echo "Changeset found."
            echo "CHANGESET_PRESENT=true" >> $GITHUB_ENV
          fi

      - name: Fail if no Changeset is present
        if: env.CHANGESET_PRESENT == 'false'
        run: |
          echo "This PR is marked for release but does not contain a Changeset file."
          echo "Please add a Changeset file to indicate the changes being released."
          exit 1
        env:
          CHANGESET_PRESENT: ${{ env.CHANGESET_PRESENT }}

      - name: Create Release Pull Request or release
        uses: changesets/action@v1
        id: changesets
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: contains(github.event.pull_request.labels.*.name, 'release:true') && github.event_name == 'push'
